<a href="https://colab.research.google.com/github/tanerant/stock_financials/blob/main/alpha.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
API_key = '3LNJOCQ5DE8V65UJ'

In [ ]:
!pip install alpha_vantage

Collecting alpha_vantage
  Downloading alpha_vantage-2.3.1-py3-none-any.whl (31 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from alpha_vantage) (3.8.6)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from alpha_vantage) (2.31.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->alpha_vantage) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->alpha_vantage) (3.3.2)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->alpha_vantage) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.10/dist-packages (from aiohttp->alpha_vantage) (4.0.3)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->alpha_vantage) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->alpha_vantage) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->alpha_vantage) (1.3.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->alpha_vantage) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->alpha_vantage) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->alpha_vantage) (2023.7.22)
Installing collected packages: alpha_vantage
Successfully installed alpha_vantage-2.3.1

In [ ]:
from alpha_vantage.timeseries import TimeSeries

In [ ]:
ts = TimeSeries(key = API_key,output_format='pandas')

df = ts.get_weekly_adjusted('IBM')
df[0]

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount
date,,,,,,,
2023-11-07,147.89,149.280,147.85,148.83,148.8300,8147102.0,0.00
2023-11-03,143.19,148.445,142.58,147.90,147.9000,22959464.0,0.00
2023-10-27,136.63,144.700,135.87,142.52,142.5200,30227448.0,0.00
2023-10-20,139.28,140.620,136.31,137.16,137.1600,21044049.0,0.00
2023-10-13,142.30,143.415,138.27,138.46,138.4600,16386334.0,0.00
...,...,...,...,...,...,...,...
1999-12-10,113.00,122.120,107.56,109.00,57.9265,58626000.0,0.00
1999-12-03,104.94,112.870,102.12,111.87,59.4517,37670000.0,0.00
1999-11-26,105.50,109.870,101.81,105.00,55.8007,37165600.0,0.00
1999-11-19,96.00,105.120,92.62,103.94,55.2374,61550800.0,0.00
1999-11-12,90.50,97.500,90.50,95.87,50.9487,43569700.0,0.12

In [ ]:
data = df[0]
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1253 entries, 2023-11-07 to 1999-11-12
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   1. open             1253 non-null   float64
 1   2. high             1253 non-null   float64
 2   3. low              1253 non-null   float64
 3   4. close            1253 non-null   float64
 4   5. adjusted close   1253 non-null   float64
 5   6. volume           1253 non-null   float64
 6   7. dividend amount  1253 non-null   float64
dtypes: float64(7)
memory usage: 78.3 KB

In [ ]:
from alpha_vantage.fundamentaldata import FundamentalData

In [ ]:
fs = FundamentalData(key = API_key,output_format='pandas')

In [ ]:
dff = fs.get_income_statement_quarterly('IBM')

In [ ]:
dff[0].T

date,1970-01-01 00:00:00.000000000,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000002,1970-01-01 00:00:00.000000003,1970-01-01 00:00:00.000000004,1970-01-01 00:00:00.000000005,1970-01-01 00:00:00.000000006,1970-01-01 00:00:00.000000007,1970-01-01 00:00:00.000000008,1970-01-01 00:00:00.000000009,1970-01-01 00:00:00.000000010,1970-01-01 00:00:00.000000011,1970-01-01 00:00:00.000000012,1970-01-01 00:00:00.000000013,1970-01-01 00:00:00.000000014,1970-01-01 00:00:00.000000015,1970-01-01 00:00:00.000000016,1970-01-01 00:00:00.000000017,1970-01-01 00:00:00.000000018,1970-01-01 00:00:00.000000019
fiscalDateEnding,2023-09-30,2023-06-30,2023-03-31,2022-12-31,2022-09-30,2022-06-30,2022-03-31,2021-12-31,2021-09-30,2021-06-30,2021-03-31,2020-12-31,2020-09-30,2020-06-30,2020-03-31,2019-12-31,2019-09-30,2019-06-30,2019-03-31,2018-12-31
reportedCurrency,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD
grossProfit,8023000000,8501000000,7509000000,9632000000,7430000000,8290000000,7335000000,9501000000,7106000000,7852000000,7027000000,5813000000,8430000000,8700000000,7922000000,6145000000,8336000000,9010000000,8043000000,10687000000
totalRevenue,14752000000,15475000000,14252000000,16690000000,14107000000,15535000000,14197000000,16694000000,13251000000,14218000000,13187000000,1926000000,17560000000,18123000000,17571000000,2344000000,18028000000,19161000000,18182000000,21761000000
costOfRevenue,6729000000,6974000000,6743000000,7058000000,6677000000,7246000000,6862000000,7195000000,6145000000,6366000000,6160000000,-3888000000,9130000000,9423000000,9649000000,-3801000000,9692000000,10151000000,10139000000,11073000000
costofGoodsAndServicesSold,42000000,61000000,30000000,190000000,57000000,120000000,19000000,89000000,49000000,103000000,59000000,181000000,64000000,117000000,76000000,387000000,75000000,74000000,55000000,11073000000
operatingIncome,1994000000,1984000000,256000000,3294000000,1471000000,2377000000,470000000,913000000,1761000000,2304000000,1084000000,-4000000000,2358000000,2121000000,-145000000,4048000000,1872000000,1950000000,1616000000,4306000000
sellingGeneralAndAdministrative,4458000000,4900000000,4853000000,4766000000,4391000000,4855000000,4597000000,4903000000,4306000000,4849000000,4688000000,4712000000,4647000000,5248000000,5955000000,3553000000,5024000000,5456000000,4691000000,4701000000
researchAndDevelopment,1685000000,1687000000,1655000000,1604000000,1611000000,1673000000,1679000000,1625000000,1606000000,1641000000,1616000000,1540000000,1515000000,1582000000,1625000000,1517000000,1553000000,1407000000,1433000000,1358000000
operatingExpenses,6029000000,6517000000,7253000000,6338000000,5959000000,5913000000,6865000000,5194000000,6410000000,6700000000,7120000000,2000000000,6072000000,6579000000,8067000000,7052000000,6464000000,7060000000,6427000000,6381000000
investmentIncomeNet,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
netInterestIncome,-412000000,-423000000,-367000000,-313000000,-295000000,-297000000,-311000000,-303000000,-291000000,-281000000,-280000000,-317000000,-323000000,-323000000,-326000000,-354000000,-432000000,-348000000,-210000000,-193000000
interestIncome,None,201000000,170000000,64000000,53000000,28000000,17000000,13000000,-1000000,11000000,14000000,15000000,15000000,23000000,51000000,48000000,63000000,167000000,70000000,None
interestExpense,412000000,423000000,367000000,313000000,295000000,297000000,311000000,303000000,290000000,281000000,280000000,317000000,323000000,323000000,326000000,354000000,432000000,348000000,210000000,193000000
nonInterestIncome,265000000,163000000,-93000000,-394000000,363000000,440000000,-42000000,None,None,None,None,None,None,None,None,None,None,None,None,None
otherNonOperatingIncome,97000000,39000000,22000000,36000000,80000000,243000000,83000000,38000000,-234000000,-315000000,-362000000,-247000000,-253000000,-179000000,-182000000,None,None,None,73000000,-184000000
depreciation,521000000,520000000,527000000,570000000,586000000,620000000,631000000,749000000,1037000000,1050000000,1052000000,1089000000,1070000000,1056000000,1012000000,1021000000,1058000000,987000000,1143000000,790000000
depreciationAndAmortization,572000000,557000000,547000000,567000000,577000000,626000000,625000000,632000000,647000000,630000000,620000000,610000000,613000000,623000000,622000000,629000000,611000000,307000000,303000000,322000000
incomeBeforeTax,1863000000,2002000000,1051000000,3154000000,-4483000000,1649000000,694000000,2739000000,906000000,1426000000,795000000,884000000,1826000000,1570000000,-51000000,3323000000,1521000000,2767000000,1880000000,4432000000
incomeTaxExpense,159000000,419000000,124000000,444000000,-1287000000,257000000,-39000000,406000000,-224000000,101000000,-160000000,-472000000,128000000,209000000,-1226000000,-347000000,-151000000,269000000,289000000,2481000000
interestAndDebtExpense,412000000,423000000,367000000,313000000,295000000,297000000,311000000,303000000,291000000,281000000,280000000,317000000,323000000,323000000,326000000,354000000,432000000,348000000,210000000,193000000
netIncomeFromContinuingOperations,1714000000,1581000000,934000000,2870000000,-3214000000,1465000000,662000000,2462000000,1037000000,810000000,403000000,-305000000,1698000000,1362000000,1176000000,1380000000,1673000000,2499000000,1593000000,1953000000
comprehensiveIncomeNetOfTax,2105000000,1863000000,888000000,3109000000,1834000000,1755000000,1436000000,5136000000,1480000000,1930000000,2036000000,603000000,1870000000,1888000000,489000000,4159000000,1427000000,2839000000,1899000000,282000000
ebit,2275000000,2425000000,1418000000,3467000000,-4188000000,1946000000,1005000000,3042000000,1196000000,1707000000,1075000000,1201000000,2149000000,1893000000,275000000,3677000000,1953000000,3115000000,2090000000,4625000000
ebitda,2847000000,2982000000,1965000000,4034000000,-3611000000,2572000000,1630000000,3674000000,1843000000,2337000000,1695000000,1811000000,2762000000,2516000000,897000000,4306000000,2564000000,3422000000,2393000000,4947000000
netIncome,1704000000,1583000000,927000000,2710000000,-3196000000,1392000000,733000000,2333000000,1130000000,1325000000,955000000,1356000000,1698000000,1361000000,1175000000,3670000000,1672000000,2498000000,1591000000,1951000000